window.PHOTO_CONCEPTS=[
{title:'형용사 자리와 분사 선택',summary:'명사 앞은 형용사 자리지만, -ing/-p.p.는 의미 관계까지 확인합니다.',rules:['활동 계열: 행동 주체는 -ing, 행동 대상은 p.p.','감정 계열은 반대 감각: 감정을 주는 사물은 -ing, 감정을 느끼는 사람은 p.p.','be동사 뒤라고 무조건 분사가 정답은 아니며 정품 형용사를 먼저 확인합니다.'],examples:['planning manager(계획하는 관리자) ↔ planned event(계획된 행사)','interesting movie(흥미를 주는 영화) ↔ pleased worker(기쁨을 느낀 직원)','be comparable in quality to ~: 품질 면에서 ~와 견줄 만하다']},
{title:'명사 뒤 형용사·분사',summary:'뒤에서 명사를 꾸미면 생략된 관계절로 복원해 뜻을 확인합니다.',rules:['a car parked = a car which is parked','명사-분사-명사 구조에서 -ing는 앞 명사를 꾸미며 뒤 명사를 목적어로 취할 수 있습니다.','p.p. 수동분사는 뒤에 목적어를 직접 끌 수 없습니다.'],examples:['a policy regulating violations = 위반을 규제하는 정책','a way of attracting customers = 고객을 유치하는 방법']},
{title:'형용사 + 전치사 핵심',summary:'형용사 자체의 뜻과 뒤 전치사를 한 덩어리로 암기합니다.',rules:['책임: responsible/accountable for','대응·관계: responsive/subject/susceptible/vulnerable to','일치·적합: compatible with, suitable/ideal/appropriate for','인식·태도: aware/cognizant/mindful of, considerate of'],examples:['be responsible for the budget','be responsive to customer requests','be subject to change ↔ be susceptible to damage']},
{title:'두 뜻·두 용법 구별',summary:'같은 단어라도 목적어와 상황이 바뀌면 TOEIC에서 뜻이 달라집니다.',rules:['conduct: 업무를 수행하다 / conduct oneself: 처신하다','decline: 수치가 감소하다 / 제안·초대를 거절하다','engagement: 약속·행사 / 참여도·관여 / 고용','variable: 변하기 쉬운(형용사) / 변수(명사)'],examples:['conduct a survey ↔ conduct oneself professionally','Sales declined. ↔ She declined the invitation.','a prior engagement ↔ employee engagement']},
{title:'assure와 convince',summary:'둘 다 사람 목적어를 취하지만 뒤 구조와 초점이 다릅니다.',rules:['assure A of B / assure A that S+V: A에게 B를 보장·확신시키다','convince A of B / convince A to V: 근거로 A를 납득시켜 행동하게 하다','Rest assured that ~: ~임을 안심하세요'],examples:['We assured clients of confidentiality.','The data convinced the board to approve the plan.']},
{title:'동사 고정 구조',summary:'전치사나 목적격 보어까지 포함한 덩어리가 정답을 결정합니다.',rules:['prevent A from V-ing','expect/encourage A to V','equip A with B','comply with + 규정','be intended for + 대상 / be intended to V + 목적'],examples:['prevent files from being sent','encourage staff to report problems','equip workers with safety gear']},
{title:'뜻이 비슷한 제외 표현',summary:'세 표현 모두 제외를 뜻하며 문장에서는 거의 교체 가능합니다.',rules:['except for + 제외 대상','with the exception of + 제외 대상: 더 격식적','apart from: 제외 외에라는 추가 의미도 문맥에 따라 가능'],examples:['All branches except for Busan will close.','With the exception of one item, the order is complete.']},
{title:'현재완료 수동태',summary:'과거에 완료된 행동의 결과가 현재까지 이어질 때 씁니다.',rules:['have/has been + p.p.','주어가 행동을 받는 대상인지 먼저 확인','복수 주어 bins/volunteers에는 have 사용'],examples:['Special bins have been placed outside.','Instructions have been sent to volunteers.']},
{title:'형용사와 동명사의 충돌',summary:'전치사 뒤라도 뒤 명사를 목적어로 끌어야 한다면 동명사가 우세합니다.',rules:['a way of attracting customers: attracting이 customers를 목적어로 취함','attractive customers는 매력적인 고객이라는 전혀 다른 뜻','관사 a/the가 명사 앞에 있어도 동명사는 동사 성질로 목적어를 취할 수 있음'],examples:['a method of reducing costs','a strategy for attracting applicants']},
{title:'비슷해 보이지만 뜻이 다른 분사·형용사',summary:'철자가 비슷해도 두 단어의 뜻이 다르면 p.p.가 정품 형용사를 이길 수 있습니다.',rules:['extended(연장된) ↔ extensive(광범위한)','constructed(건설된) ↔ constructive(건설적인)','repeated(반복된) ↔ repeatable(반복 가능한)','preferred(선호되는) ↔ preferable(더 나은)','related(관련된) ↔ relative(상대적인/친척)'],examples:['an extended deadline ↔ extensive experience','a preferred supplier ↔ a preferable option','related documents ↔ relative importance']},
{title:'빈도·정도 부사의 위치',summary:'행동이나 상태 전체를 꾸미면 형용사가 아니라 부사를 고릅니다.',rules:['more + 부사 + than necessary','be동사 뒤 빈도부사: buses are rarely on time','일반동사 앞 빈도부사: employees usually arrive early'],examples:['Do not restart it more frequently than necessary.','City buses are rarely on time.']},
{title:'시점·기간 표현',summary:'시작 시점, 기간 전체, 정시 여부를 구분합니다.',rules:['as of + 시점: ~부로','throughout + 기간: ~내내','punctually/on time: 정시에','by then: 그때까지(마감 시점)'],examples:['As of today, the policy is effective.','The desk is open throughout the day.','Payment must arrive by then.']},
{title:'뜻이 비슷한 가산·불가산 명사',summary:'한국어 뜻이 비슷해도 개별 대상인지 활동·집합·추상 개념인지에 따라 셈 여부가 달라집니다.',rules:['fund(하나의 기금) / funds(자금) ↔ funding(자금 지원·조달)','permit(허가증) ↔ permission(허가)','product·item(개별 제품) ↔ merchandise(상품 전체)','machine(개별 기계) ↔ machinery(기계류)','estimate(견적서), agreement(합의서), contract(계약서)는 개별 문서라 가산','attendance·participation·marketing·accounting은 활동·분야를 뜻할 때 불가산'],examples:['The project needs additional funding. / The city created a special fund.','You need permission to enter. / Please display the permit.','Several products were recalled. / Damaged merchandise was removed.']}
];
