window.CONCEPT_QUESTIONS=[
{id:'cq001',category:'개념 확인',label:'-ing vs p.p.',q:'The ______ manager presented the ______ event schedule.',choices:['planning / planned','planned / planning','planning / planning','planned / planned'],answer:0,translation:'기획 담당 관리자가 예정된 행사 일정을 발표했다.',why:'manager는 계획하는 주체이므로 planning, event는 계획되는 대상이므로 planned가 맞습니다.',wrongReasons:['A. planning / planned: 주체와 대상의 관계를 모두 충족하는 정답입니다.','B. planned / planning: 관리자와 행사의 능동·수동 관계가 뒤바뀝니다.','C. planning / planning: event가 스스로 계획한다는 뜻이 됩니다.','D. planned / planned: manager가 계획되는 대상이라는 부자연스러운 뜻입니다.'],wrong:'분사가 꾸미는 명사와 능동·수동 관계를 확인해야 합니다.',memory:'활동 주체 사람명사: -ing / 행동 대상 사물명사: p.p.'},
{id:'cq002',category:'개념 확인',label:'-ing vs p.p.',q:'The ______ movie kept the audience thoroughly ______.',choices:['interested / interesting','interesting / interested','interested / interested','interesting / interesting'],answer:1,translation:'그 흥미로운 영화는 관객이 계속 큰 흥미를 느끼게 했다.',why:'영화는 감정을 일으키므로 interesting, 관객은 감정을 느끼므로 interested입니다.',wrongReasons:['A. interested / interesting: 감정을 주는 대상과 느끼는 사람의 관계가 반대입니다.','B. interesting / interested: 정답입니다.','C. interested / interested: movie에 감정 수동형을 쓰면 부자연스럽습니다.','D. interesting / interesting: audience가 감정을 일으키는 뜻이 됩니다.'],wrong:'감정분사는 사물 -ing, 감정을 느끼는 사람 p.p.가 기본입니다.',memory:'interesting movie / interested audience'},
{id:'cq003',category:'개념 확인',label:'A vs B',q:'The manager is responsible ______ preparing the monthly budget.',choices:['to','with','for','of'],answer:2,translation:'그 관리자는 월간 예산을 준비할 책임이 있다.',why:'be responsible for가 고정 결합이며 전치사 뒤에는 V-ing가 옵니다.',wrongReasons:['A. to: responsible과 책임 대상을 연결하지 않습니다.','B. with: compatible with 등과 혼동한 선택지입니다.','C. for: 정답입니다.','D. of: responsible of는 표준 결합이 아닙니다.'],wrong:'형용사와 전치사를 한 덩어리로 외워야 합니다.',memory:'be responsible for + N/V-ing'},
{id:'cq004',category:'개념 확인',label:'A vs B',q:'Customer service representatives should be responsive ______ client requests.',choices:['for','to','of','with'],answer:1,translation:'고객 서비스 담당자는 고객 요청에 신속히 대응해야 한다.',why:'be responsive to는 ~에 반응하다·대응하다는 고정 표현입니다.',wrongReasons:['A. for: 책임을 뜻하는 responsible for와 혼동한 선택지입니다.','B. to: 정답입니다.','C. of: responsive와 결합하지 않습니다.','D. with: compatible with와 혼동한 선택지입니다.'],wrong:'responsive 뒤에는 to가 옵니다.',memory:'be responsive to requests'},
{id:'cq005',category:'개념 확인',label:'A vs B',q:'All prices listed in the catalog are subject ______ change without notice.',choices:['for','with','to','at'],answer:2,translation:'카탈로그에 표시된 모든 가격은 예고 없이 변경될 수 있다.',why:'be subject to change는 변경될 수 있다는 고정 표현입니다.',wrongReasons:['A. for: subject와 해당 의미로 결합하지 않습니다.','B. with: 표준 결합이 아닙니다.','C. to: 정답입니다.','D. at: 표준 결합이 아닙니다.'],wrong:'subject to를 한 단위로 기억해야 합니다.',memory:'be subject to change'},
{id:'cq006',category:'개념 확인',label:'A vs B',q:'The firm will ______ a survey before revising the product.',choices:['conduct','conduct itself','decline','engage'],answer:0,translation:'그 회사는 제품을 수정하기 전에 설문조사를 실시할 것이다.',why:'conduct a survey는 설문조사를 실시하다는 동사+목적어 콜로케이션입니다.',wrongReasons:['A. conduct: 정답입니다.','B. conduct itself: 처신하다는 별도 용법이라 목적어 a survey와 맞지 않습니다.','C. decline: 감소하다·거절하다라는 뜻입니다.','D. engage: engage in 구조가 필요합니다.'],wrong:'conduct의 목적어에 따라 뜻이 달라집니다.',memory:'conduct a survey / conduct oneself professionally'},
{id:'cq007',category:'개념 확인',label:'A vs B',q:'Ms. Kim politely ______ the invitation because of a prior engagement.',choices:['decreased','declined','lowered','reduced'],answer:1,translation:'김 씨는 선약 때문에 그 초대를 정중히 거절했다.',why:'decline은 수치가 감소하다는 자동사 용법뿐 아니라 초대·제안을 거절하다는 타동사 용법도 있습니다.',wrongReasons:['A. decreased: 수치가 감소했다는 뜻으로 invitation을 목적어로 쓰기 부자연스럽습니다.','B. declined: 정답입니다.','C. lowered: 가격·수준 등을 낮추다는 뜻입니다.','D. reduced: 양·비용 등을 줄이다라는 뜻입니다.'],wrong:'목적어 invitation이 decline의 거절 의미를 결정합니다.',memory:'sales decline / decline an invitation'},
{id:'cq008',category:'개념 확인',label:'A vs B',q:'The data convinced the board ______ the revised proposal.',choices:['approving','approve','to approve','approved'],answer:2,translation:'그 자료는 이사회가 수정된 제안을 승인하도록 납득시켰다.',why:'convince A to V 구조이므로 to approve가 맞습니다.',wrongReasons:['A. approving: 목적격 보어 자리에 동명사를 쓰지 않습니다.','B. approve: to 없는 원형은 올 수 없습니다.','C. to approve: 정답입니다.','D. approved: 이사회가 승인된 대상이라는 뜻이 되어 맞지 않습니다.'],wrong:'convince 뒤의 사람 목적어 다음에는 to부정사가 옵니다.',memory:'convince A to V / assure A that S+V'},
{id:'cq009',category:'개념 확인',label:'A vs B',q:'The security system prevents confidential files from ______ externally.',choices:['send','being sent','sent','be sending'],answer:1,translation:'보안 시스템은 기밀 파일이 외부로 전송되는 것을 막는다.',why:'files는 전송되는 대상이므로 from 뒤에 수동 동명사 being sent가 필요합니다.',wrongReasons:['A. send: 전치사 뒤에 동사원형을 쓸 수 없습니다.','B. being sent: 정답입니다.','C. sent: from 뒤에는 동명사 형태가 필요합니다.','D. be sending: from 뒤의 올바른 동명사 수동형이 아닙니다.'],wrong:'prevent A from V-ing에서 A와 동작의 능동·수동 관계도 확인합니다.',memory:'prevent A from being p.p.'},
{id:'cq010',category:'개념 확인',label:'A vs B',q:'______ today, the revised policy applies to every branch.',choices:['Throughout','As of','By then','Punctually'],answer:1,translation:'오늘부로 개정된 정책은 모든 지점에 적용된다.',why:'특정 시점부터 적용된다는 뜻에는 as of가 맞습니다.',wrongReasons:['A. Throughout: 기간 전체를 뜻하며 today 앞에서는 문맥이 다릅니다.','B. As of: 정답입니다.','C. By then: 그때까지라는 마감 의미입니다.','D. Punctually: 정시에라는 부사입니다.'],wrong:'시작 시점과 기간 전체를 구분해야 합니다.',memory:'as of + 시점 / throughout + 기간'},
{id:'cq011',category:'개념 확인',label:'A vs B',q:'The company selected its ______ supplier because the second option was not ______.',choices:['preferable / preferred','preferred / preferable','preferred / preferred','preferable / preferable'],answer:1,translation:'회사는 두 번째 선택지가 더 낫지 않았기 때문에 선호하는 공급업체를 선정했다.',why:'preferred는 선호되는, preferable은 비교하여 더 나은이라는 뜻입니다.',wrongReasons:['A. preferable / preferred: supplier와 option의 의미가 뒤바뀝니다.','B. preferred / preferable: 정답입니다.','C. preferred / preferred: 두 번째 자리는 더 낫다는 비교 의미가 필요합니다.','D. preferable / preferable: 첫 번째 자리는 선호되는 공급업체라는 뜻이 자연스럽습니다.'],wrong:'철자가 비슷해도 의미가 다른 정품 형용사입니다.',memory:'preferred supplier / preferable to another option'},
{id:'cq012',category:'개념 확인',label:'A vs B',q:'The marketing team is developing a strategy for ______ new customers.',choices:['attractive','attracting','attraction','attractively'],answer:1,translation:'마케팅팀은 신규 고객을 유치하기 위한 전략을 개발하고 있다.',why:'for 뒤에서 customers를 목적어로 취하는 동명사 attracting이 필요합니다.',wrongReasons:['A. attractive: attractive customers는 매력적인 고객이라는 다른 뜻입니다.','B. attracting: 정답입니다.','C. attraction: 명사라 customers를 목적어로 취할 수 없습니다.','D. attractively: 부사는 목적어를 취할 수 없습니다.'],wrong:'전치사 뒤라도 뒤 명사를 목적어로 끌면 동명사가 필요합니다.',memory:'a strategy for attracting customers'}
];
