const dayQuestions=[];
function D(day,n,q,c,a,e){dayQuestions.push({id:`d${day}-${n}`,day:`DAY ${day}`,tag:`DAY ${day}`,q,c,a,e:e||`정답은 ${c[a]}입니다.`})}
// DAY 1 — Word 통합 문제지 1~30
D(1,1,'After a thorough review of all the suggestions, it was clear that ______ was the most realistic proposal.',['us','we','ours','ourselves'],2);
D(1,2,'All exercise equipment in the Ultimate Fitness has been replaced in its ______ with new machines from Loctek Ergonomic.',['entirety','demand','storage','capacity'],0);
D(1,3,'Campus volunteer ______ consent to the partnership with local organizations to expand community service opportunities.',['coordinates','coordination','coordinators','coordinated'],2);
D(1,4,'After searching for hours, Ms. Mackensie finally decided to shop ______ Interior Define for custom furniture that matched her style perfectly.',['for','before','with','into'],2);
D(1,5,'Due to Corner Café being an important ______, we need to handle their rush order with the highest priority.',['contract','promotion','speaker','account'],3);
D(1,6,'When checking the office equipment, please record ______ system failures in the green box on Ms. Ryoko’s desk.',['which','that','every','any'],3);
D(1,7,'At Max Cargo Company, there are several ______ job openings for delivery truck drivers with at least 3 years of industry experience.',['immediate','talented','direct','classic'],0);
D(1,8,'The Nevada Transport Authority’s recent analysis of cities with subway systems ______ omitted Boulder City from its report.',['steadily','inadvertently','sustainably','independently'],1);
D(1,9,'Clio Snacks’ design team has developed new packaging ideas that can improve product ______.',['protects','protection','protector','protectively'],1);
D(1,10,'______ the company’s business calendar is now posted online, paper copies will no longer be distributed.',['Regardless of','Since','In case of','Besides'],1);
D(1,11,'Included in the information packet are three meal vouchers, ______ will allow you to eat at Leticore Hotel’s in-house restaurant.',['where','whose','which','what'],2);
D(1,12,'Rebecca Madison, staff writer at Boston Daily, writes only ______ about fashion, preferring to focus primarily on local news and culture.',['occasion','occasions','occasional','occasionally'],3);
D(1,13,'K.L. Home Deco has a ______ selection of home furnishings in its showroom in Melbourne.',['various','fascinated','limited','largest'],0);
D(1,14,'Stock prices nearly doubled at the first part of the day and then ______ off.',['standardized','downgraded','leveled','commenced'],2);
D(1,15,'A scheduling conflict prevented Mr. Keita ______ attending the investor’s meeting.',['with','from','after','while'],1);
D(1,16,'The purpose of Professor Leonard’s study is to ______ the effects that office lighting has on employee productivity.',['prohibit','measure','accomplish','influence'],1);
D(1,17,'It is ______ common for new restaurants to fail to develop a menu to attract customers at first.',['reasonably','fairly','evenly','occasionally'],1);
D(1,18,'You should be ______ of other people’s points of view during staff meetings.',['respect','respective','respectful','respected'],2);
D(1,19,'A sales ______ from Vallejo Beverages will address student interns participating in the winter internship program.',['agreement','conference','projection','representative'],3);
D(1,20,'The recently released movie Days of Glory has been well ______ in Korea and the United States.',['opposed','creative','positive','received'],3);
D(1,21,'Utility costs such as water, electricity, and gas are included in the rental price unless ______ specified in the rental agreement.',['once','sooner','otherwise','eventually'],2);
D(1,22,'The Global Glass Manufacturers Council ______ the interests of glass manufacturers around the world.',['represents','reproduces','contributes','operates'],0);
D(1,23,'Mr. Himura has been ______ involved in the development of Visetrix wireless headsets.',['commonly','occasionally','deeply','fondly'],2);
D(1,24,'Mr. Martinelli, ______ started as a stock clerk and is now vice president of marketing, will retire in May.',['who','that','whom','himself'],0);
D(1,25,'The cost of additional exterior paint has been factored ______ the revised estimate.',['into','out','with','upon'],0);
D(1,26,'The letter regarding the proposed ______ of Marcie Law Office by Kapoor Legal Services has arrived.',['acquisition','detachment','document','compliance'],0);
D(1,27,'All laboratory ______ must annually complete a course in safety practices.',['researcher','network','test','personnel'],3);
D(1,28,'Due to unusually high demand, ______ of our lawn supplies need to be restocked.',['some','something','other','each other'],0);
D(1,29,'For three years, you are ______ obligated to pay a 10% commission fee to Aloz Financial every two months.',['responsibly','considerably','contractually','confidently'],2);
D(1,30,'Mr. Karl appears ______ to take on more duties and to have more control over important decisions.',['capable','determined','likable','ambitious'],1);
// DAY 2 — 101~138
D(2,101,'As Kamon Machines discontinued producing replacement parts for old fax machine models, we cannot purchase ______ anymore.',['they','them','their','theirs'],1);
D(2,102,'Mr. Jones has been ______ recommended by most of his former employers.',['high','higher','highest','highly'],3);
D(2,103,'______ at the city festival was significantly lower because the date of the parade was changed with little advance notice.',['Attend','Attendance','Attendees','Attendants'],1);
D(2,104,'Tang Toys increased its second-quarter revenue thanks to the continued ______ of sales in Japan and America.',['assets','expansion','decline','compensation'],1);
D(2,105,'The shipping manager is worried about making the ______ date because of the record snowfall yesterday.',['deliver','delivers','delivery','delivered'],2);
D(2,106,'Komi Motors has overcome the global economic crisis by ______ its manufacturing plant in Eastern Europe.',['close','closing','closed','closes'],1);
D(2,107,'The Fashion Academy has produced ______ professional designers for the competitive fashion industry.',['create','creation','creative','creatively'],2);
D(2,108,'______ it was snowing heavily, many people decided to walk to work to avoid traffic in town.',['Besides','Instead of','Apart from','Even though'],3);
D(2,109,'According to the yearly sales report, the Genelec Factory’s revenue showed ______ improvement after restructuring.',['wealthy','significant','comparing','worsening'],1);
D(2,110,'In the early 20th century, it was quite an ______ experience to travel about 50 miles due to inadequate transportation infrastructure.',['excite','exciting','excited','excitedly'],1);
D(2,111,'Smoking is not allowed inside the petroleum storage area, ______ is it allowed near the petrochemical plant.',['unless','whether','nor','besides'],2);
D(2,112,'All the residents without exception are ______ to evacuate the building during a fire drill.',['spoken','described','asked','realized'],2);
D(2,113,'______ located in the business district, the duty-free shops will open their doors to international tourists.',['Strategy','Strategize','Strategic','Strategically'],3);
D(2,114,'Even though Jason Heavy Industries received many applications, few individuals were ______ trained.',['qualify','qualifies','qualified','qualifications'],2);
D(2,115,'From casinos and shows to fine dining, Las Vegas ______ a world-class vacation destination.',['remains','stays','locates','appears'],0);
D(2,116,'Please be ______ that international bank processing times vary depending on the local banking system.',['advise','advised','advisable','advisory'],1);
D(2,117,'The old industrial park and the ______ property have been redeveloped into a new apartment complex.',['surround','surrounds','surrounded','surrounding'],3);
D(2,118,'Please list the results of Mr. Watson’s research on the final slide ______ the marketing presentation.',['within','of','through','except'],0);
D(2,119,'Most people think art is for the highly gifted or for ______.',['profession','professional','professionals','professionally'],2);
D(2,120,'To prevent workplace accidents, it is ______ that all employees take part in annual safety training.',['ambiguous','mandatory','preventive','appreciative'],1);
D(2,121,'At regular marketing meetings, Mr. Thompson ______ offers innovative strategies.',['frequently','enormously','considerably','promptly'],0);
D(2,122,'______ she quit her job last week, Ms. Parker has time to take a management course.',['Since','When','Despite','Therefore'],0);
D(2,123,'Once employees complete the training, they will be ______ at doing their accounting work.',['flexible','aware','proficient','economical'],2);
D(2,124,'Our survey indicated that most consumers ______ mint-flavored chocolate chips very appetizing.',['take','find','expect','feel'],1);
D(2,125,'According to the revised regulations, ______ of the member nations must undergo periodic audits.',['all','another','every','few'],0);
D(2,126,'The insurance company attempted to ______ the fire damage as accurately as it could.',['avoid','cover','appraise','claim'],2);
D(2,127,'If your bag is not found within 21 days, we will ______ you for any transportation fee.',['provide','reimburse','transfer','allocate'],1);
D(2,128,'Some reasons for the decrease in housing sales are not ______ clear.',['apparently','usually','meticulously','immediately'],0);
D(2,129,'Regardless of ______ an applicant is offered a loan, all applications must be kept for a year.',['whereas','even though','instead','whether'],3);
D(2,130,'If the company ______ to our demands reasonably, the union will resume negotiations.',['respond','responds','will respond','was responding'],1);
D(2,131,'John Baker, a renowned performance director, ______ us a guided tour next Saturday.',['giving','will be giving','was given','give'],1);
D(2,132,'Which sentence best fits the Warren Hall tour memorandum?',['All employees are advised to attend.','A small amount was spent on donations.','It has been praised for its sets and costumes.','Many films will be shown there.'],2);
D(2,133,'______ there is no charge for the tour, every employee must reserve a spot.',['Even if','Since','When','Although'],3);
D(2,134,'Please be ______ that tickets are limited and sign-up ends June 30.',['reluctant','possible','willing','aware'],3);
D(2,135,'Starting in January, Taylor & Murphy Accounting ______ all computer maintenance and data management operations.',['will be outsourcing','outsourced','have been outsourced','outsourcing'],0);
D(2,136,'We expect partner employees on site. ______, we understand that this may not always be possible.',['While','Even','Furthermore','However'],3);
D(2,137,'Extra work will be needed at the start ______ upgrade copper-based networks to fiber optics.',['so that','in order to','which','in case'],1);
D(2,138,'Which sentence best completes the accounting company’s bid letter?',['All proposals and bids must be received by August 31.','Many bidders will compete for the contract.','Paperwork accuracy is important.','Our personnel can improve your efficiency.'],0);
// DAY 3 — 101~146
D(3,101,'The residents supported several politicians ______ believed to be the most honest and prudent.',['they','their','their own','theirs'],0);
D(3,102,'Whoever is willing to ______ today’s informational seminar may do so.',['detect','achieve','attend','notify'],2);
D(3,103,'The company’s best sales ______ was attributable to Mr. Yamada’s team.',['performed','preforms','performing','performance'],3);
D(3,104,'The Empire Hotel is accepting applications from ______ individuals.',['angular','aligned','exceptional','farther'],2);
D(3,105,'Although many ______ a profitable holiday season, the company is concerned about labor costs.',['expect','expectation','are expected','expectantly'],0);
D(3,106,'Night-shift representatives are available ______ 6:00 P.M. to 2:00 A.M.',['between','from','since','beyond'],1);
D(3,107,'Liam Body Care has been a major ______ of massage services for almost 20 years.',['provide','provision','provider','provided'],2);
D(3,108,'Engineers will publicize the results of the ______ into alternative energy.',['understanding','determination','investigation','specification'],2);
D(3,109,'Most of the ______ institutes in Korea are struggling because of online banks.',['financial','financing','finances','financially'],0);
D(3,110,'______ passengers vary in their seat preferences, they can choose seats online.',['Whether','Soon','Why','Since'],3);
D(3,111,'The LCG’s new monitor ______ with a surround-sound speaker and a display stand.',['comes','will come','is come','was coming'],0);
D(3,112,'Only 5 participants finished because it was ______ hot.',['importantly','almost','closely','uncomfortably'],3);
D(3,113,'The board had a strategy meeting on its goals ______ the next fiscal year.',['under','for','alongside','as'],1);
D(3,114,'Albright Media Cable will start a channel ______ to sports and entertainment news.',['permitted','introduced','reported','dedicated'],3);
D(3,115,'Ms. Sutherland finished her work ______ several days before the deadline.',['completely','completed','complete','completing'],0);
D(3,116,'The estimate will be sent ______ the due date.',['along','within','through','before'],3);
D(3,117,'Faced with residents’ reactions, the mayor will ______ approve the proposal.',['lately','finally','infinitely','lastly'],1);
D(3,118,'Due to an increase in ______, customers should expect shipment delays.',['seniority','arrival','demand','certificate'],2);
D(3,119,'Yoon’s Catering offers food items at ______ prices.',['reason','reasonable','reasonably','reasons'],1);
D(3,120,'______ several workers are hired, meeting the construction schedule will not be a problem.',['Except for','Since','Instead of','If'],3);
D(3,121,'The mayor’s contribution was ______ recognized and appreciated.',['widely','wide','wideness','widening'],0);
D(3,122,'Ms. Ayasha kindly ______ a job offer that did not meet her salary expectations.',['prevented','removed','declined','obtained'],2);
D(3,123,'Most staplers are missing, so please bring back ______ ones you took.',['what','whichever','whom','whose'],1);
D(3,124,'______ our CEO does not return next week, meeting rooms will be reserved.',['Although','Even if','Nearly','Despite that'],1);
D(3,125,'Our manager will be available for ______ one hour due to a meeting.',['no more than','hardly any','as soon as','that much'],0);
D(3,126,'The president cautioned that ______ news about him was everywhere and untrue.',['overall','biased','lucrative','modest'],1);
D(3,127,'The most important ______ job candidates must have is diligence.',['act','type','trait','fact'],2);
D(3,128,'Technicians concluded the network problems were the same as those found ______.',['elsewhere','within','otherwise','where'],0);
D(3,129,'All board members are ______ of the success of the organic pet treats.',['convinced','convincing','have convinced','will be convinced'],0);
D(3,130,'The jump in oil prices can be ______ to political uncertainty.',['removed','established','attributed','enlarged'],2);
D(3,131,'Heather has a great deal of respect for the ballet school’s ______.',['exhibition','institute','theater','store'],1);
D(3,132,'She would be ______ to contribute as a dance instructor.',['delighting','delight','delights','delighted'],3);
D(3,133,'She has worked with dancers of many ages. ______, she can adjust her teaching style.',['Otherwise','In addition','Consequently','However'],2);
D(3,134,'Which sentence best completes Heather’s application e-mail?',['I can teach injury prevention.','Download the app to join a class.','I learned from your class.','You can view my dancing videos online.'],3);
D(3,135,'The hotel’s special 30% discount ______ is available throughout March.',['tour','performance','edition','rate'],3);
D(3,136,'______ with calming colors, the deluxe rooms are perfect for relaxing.',['Decorating','To decorate','They decorated','Decorated'],3);
D(3,137,'______ come with a king-sized bed, kitchenette, and spacious bathroom.',['They','Either','Whichever','Fewer'],0);
D(3,138,'Which sentence best completes the hotel Web page?',['A breakfast buffet is served daily.','The card will not be charged until 24 hours before check-in.','Staff will accommodate this request.','Many downtown hotels have vacancies.'],1);
D(3,139,'Thank you for informing us ______ the missed recycling collection.',['with','until','about','into'],2);
D(3,140,'We dispatched a short-notice pickup team. ______, your recycling will be collected by 4 P.M.',['For instance','On the other hand','Apart from that','For this reason'],3);
D(3,141,'Which sentence best explains why replacement crews are working?',['We cannot take unclean items.','Leave feedback on the city site.','A schedule is attached.','Due to the holiday, replacement crews are working this week.'],3);
D(3,142,'Your feedback helps us to ______ our service commitment.',['fulfillment','fulfill','fulfilling','fulfilled'],1);
D(3,143,'Consumers found the handbag ad campaign less ______ than expected.',['gradual','compelling','repetitive','doubtful'],1);
D(3,144,'The design team will receive several ______ outlined by the research team.',['specifying','specification','specifications','specifies'],2);
D(3,145,'Which sentence best completes the handbag development memo?',['Less expensive materials are available.','The commercial features employees.','Next, we will gather feedback from potential customers.','Your efforts made a difference.'],2);
D(3,146,'The additional work will be difficult ______ beneficial.',['for','as','yet','if'],2);
