const R=(id,category,q,choices,translation,why,reasons,memory)=>({id,category,label:'',q,choices,answer:0,translation,why,wrongReasons:reasons.map((x,i)=>`${'ABCD'[i]}. ${choices[i]}: ${x}`),wrong:'동사의 구조·시제·명사의 가산성을 함께 확인하세요.',memory,source:'이전 FINAL_ENHANCED 원본 복구'});
window.RESTORED_CORE_QUESTIONS=[
R('rf001','동사 형식','The consultant ______ us useful advice.',['gave','explained','discussed','said'],'그 컨설턴트는 우리에게 유용한 조언을 해 주었다.','give + 사람 + 사물의 4형식입니다.',['give A B를 완성하는 정답입니다.','explain B to A로 써야 합니다.','사람+사물의 4형식으로 쓰지 않습니다.','say B to A로 써야 합니다.'],'give A B / explain B to A'),
R('rf002','동사 형식','The new software ______ easy to use.',['seems','makes','gives','explains'],'그 새 소프트웨어는 사용하기 쉬워 보인다.','seem은 형용사 보어를 취하는 2형식 연결동사입니다.',['seems easy가 되어 정답입니다.','이 뜻에서는 목적어가 필요합니다.','목적어가 필요합니다.','설명할 목적어가 필요합니다.'],'seem/look/appear + 형용사'),
R('rf003','동사 형식','The policy will ______ employees to work remotely.',['allow','suggest','mention','occur'],'그 정책은 직원들이 원격으로 근무할 수 있게 할 것이다.','allow + 목적어 + to V의 5형식입니다.',['allow A to V의 정답입니다.','suggest V-ing/that절을 씁니다.','A to V 구조를 만들지 않습니다.','“발생하다”라는 자동사입니다.'],'allow/enable/encourage A to V'),
R('rf004','동사 형식','The shipment ______ yesterday afternoon.',['arrived','reached','delivered','sent'],'그 배송품은 어제 오후에 도착했다.','arrive는 목적어 없이 쓰는 1형식 자동사입니다.',['목적어 없이 완전하므로 정답입니다.','타동사라 목적어가 필요합니다.','배송품은 배달되는 대상이므로 was delivered가 필요합니다.','배송품은 보내지는 대상이므로 was sent가 필요합니다.'],'arrive at/in + 장소 / reach + 장소'),
R('rt001','동사 시제','The company ______ its policy since January.',['has revised','revised','will revise','revises'],'그 회사는 1월부터 지금까지 정책을 개정해 왔다.','since January는 과거부터 현재까지를 나타내므로 현재완료가 맞습니다.',['과거와 현재를 연결하는 정답입니다.','끝난 과거만 나타냅니다.','미래시제입니다.','일반적·반복적 사실을 나타냅니다.'],'have/has p.p. + since 시작점'),
R('rt002','동사 시제','By the time we arrived, the meeting ______.',['had begun','has begun','begins','will begin'],'우리가 도착했을 때에는 회의가 이미 시작된 뒤였다.','과거의 도착 시점보다 회의 시작이 먼저이므로 과거완료가 맞습니다.',['과거 기준점보다 앞선 일을 나타냅니다.','현재완료라 과거 기준점과 맞지 않습니다.','단순현재입니다.','미래시제입니다.'],'By the time + 과거, 주절 had p.p.'),
R('rt003','동사 시제','When the director ______, we will begin.',['arrives','will arrive','arrived','has arriving'],'이사가 도착하면 우리는 시작할 것이다.','미래 의미라도 when 시간 부사절에서는 현재시제를 씁니다.',['시간 부사절의 현재시제로 정답입니다.','시간 부사절 안에는 보통 will을 쓰지 않습니다.','과거시제입니다.','문법적으로 틀리며 완료형은 has arrived입니다.'],'when + 현재, 주절 will V'),
R('rt004','동사 시제','The package ______ yesterday.',['was delivered','has delivered','delivers','is delivering'],'그 소포는 어제 배달되었다.','과거 시점이고 소포는 배달되는 대상이므로 과거 수동태가 맞습니다.',['과거와 수동을 모두 충족합니다.','현재완료 능동형입니다.','단순현재 능동형입니다.','현재진행 능동형입니다.'],'yesterday → 과거 / be p.p. → 수동'),
R('rc001','가산·불가산','The manager gave us several useful ______.',['suggestions','advice','equipment','furniture'],'그 관리자는 우리에게 몇 가지 유용한 제안을 해 주었다.','several 뒤에는 복수 가산명사가 와야 합니다.',['복수 가산명사라 정답입니다.','불가산명사입니다.','불가산명사입니다.','불가산명사입니다.'],'several suggestions / pieces of advice'),
R('rc002','가산·불가산','There is not ______ time remaining.',['much','many','a few','several'],'남아 있는 시간이 많지 않다.','“시간”의 time은 불가산명사이므로 much가 맞습니다.',['불가산명사의 양을 나타냅니다.','복수 가산명사 앞에 씁니다.','복수 가산명사 앞에 씁니다.','복수 가산명사 앞에 씁니다.'],'much time / many times(여러 번)'),
R('rc003','가산·불가산','Only a few ______ attended the workshop.',['employees','staff','personnel','equipment'],'소수의 직원들만 워크숍에 참석했다.','a few 뒤에는 복수 가산명사가 필요합니다.',['복수 가산명사라 정답입니다.','a few staff members가 자연스럽습니다.','a few personnel members가 자연스럽습니다.','불가산명사이며 사람도 아닙니다.'],'a few employees / a few staff members'),
R('rc004','가산·불가산','The office purchased new ______.',['equipment','equipments','an equipment','many equipment'],'그 사무실은 새 장비를 구입했다.','equipment는 불가산명사이므로 관사나 복수형 없이 씁니다.',['올바른 불가산 형태입니다.','일반적으로 복수형을 쓰지 않습니다.','부정관사를 쓰지 않습니다.','many는 복수 가산명사와 결합합니다.'],'a piece of equipment / pieces of equipment')
];
